### ISSUE TITLE
Can hash numpy.arrays in decorator

### ISSUE THREAD

**Issue by breznak** [pbrady/fastcache#37]
Hello, 
I'd like to use fastcache for my code, but my function is using ndarray. 

the decorator `@clru_cache` cannot be used for functions with `numpy.array()` arguments, as those can't be hashed directly. 
We must hash the underlying buffer: 
```
myarr.flags.writeable = False
hash(myarr.data)
``` 

This would have some overhead but should make it more convenient to use your library for these data. 
Thanks

**Comment by pbrady** [comment]
@breznak, it could be a rather severe performance penalty to have fastcache check the type of every argument and to see if it's an ndarray.  It certainly something that someone could do on a per-project basis by wrapping clru_cache.  As an example, you can take a look at the python wrapper [lru_cache] (https://github.com/pbrady/fastcache/blob/master/fastcache/__init__.py#L30).

**Comment by breznak** [comment]
That makes sense, closing. Thanks!
