### ISSUE TITLE
Improve use for libraries, how set params at runtime?

### ISSUE THREAD

**Issue by breznak** [pbrady/fastcache#40]
I'd love to use `fastcache` in my library, but for that I can't set `maxsize` parameter of fastcache myself, but need to assign it at runtime. 

I have tried to write my decorator, but with mixed success: the decorator works (albeit ugly, many nested levels) but it breaks the `cache_info()` statistics which is needed for testing. 

Let's give an example of my usecase:
```
class A:
  @cached
  def foo_long(arg1, ..)
```

How to get the arguments to fastcache?:
* "cached" method will have an argument `cachesize` which would be read by the decorator: 
```
@cached
def foo_long(arg1, cachesize=1000):
```
* or fastcache takes optional argument `readFrom`: string, that will define a name of instance member variable holding the value for fastcache: 
```
@cached(readFrom='_cacheSize')
def foo_long(arg1):
```

Bonus points which I couldn't achieve:
* make `cache_info()` work with these decorators
* adapt clru_cache to use this code, so I don't have to use the lru_cache python wrapper.

What do you think about these suggestions? Thanks

**Comment by pbrady** [comment]
fastcache is used in sympy where the maximum cache size is controlled by an environment variable that is processed at run-time.  You can examine the decorator that is used to make this happen at https://github.com/sympy/sympy/blob/master/sympy/core/cache.py#L108.  Let me know if have any questions about how to apply it to your code.

**Comment by breznak** [comment]
Peter, thank you for the pointer to `sympy`'s cache! I'll try to adapt their decorator to read a reference to an object's variable. 
Btw, I've opened an issue to improve the runtime argument handling at the python's lru_cache at 
https://bugs.python.org/issue24969
but I'm not sure how welcome it is :) I'd like to avoid the hassle of decorators around decorators.
