### ISSUE TITLE
Python 2.6+ compatibility

### ISSUE THREAD

**Issue by breznak** [pbrady/fastcache#41]
There's quite easy step to add a python 2.6+ compatibility. 
Your code is compatible, only problem is is in the benchmark which uses `functools.lru_cache` from python 3.3+; 

Please modify the benchmark script to use the backport: 
https://pypi.python.org/pypi/backports.functools_lru_cache/1.0.1

**Comment by funkyfuture** [comment]
this issue is obsolete, isn't it?

**Comment by pbrady** [comment]
Yep
