### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by basnijholt** [pbrady/fastcache#53]
Related to https://github.com/pbrady/fastcache/issues/47.

However, even without wheels, it would be good to upload the package to PyPI.

This solves [this](https://github.com/sympy/sympy/issues/16030) problem for me (and lots of others).

**Comment by pbrady** [comment]
Thanks for opening the issue.  I'll try to do this in the next few days.

**Comment by pbrady** [comment]
Done!
